# Generated by Django 5.0.6 on 2024-05-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedviewer', '0003_topic_alter_message_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
