# Generated by Django 5.0.6 on 2024-05-23 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='tag',
        ),
        migrations.AddField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='link',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='title',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topics',
            name='url',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together={('label', 'theme')},
        ),
        migrations.CreateModel(
            name='MessageTags',
            fields=[
                ('messageid', models.OneToOneField(db_column='messageid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='graphs.messages')),
                ('tagid', models.ForeignKey(db_column='tagid', on_delete=django.db.models.deletion.DO_NOTHING, to='graphs.tags')),
            ],
            options={
                'db_table': 'message_tags',
                'managed': True,
                'unique_together': {('messageid', 'tagid')},
            },
        ),
    ]
