# Generated by Django 5.0.6 on 2024-05-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'managed': True},
        ),
    ]
