# Generated by Django 5.0.6 on 2024-05-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_alter_topics_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'managed': True},
        ),
    ]
